"""actual table creation

Revision ID: 95e9a773f3b8
Revises: 
Create Date: 2026-01-18 00:40:07.126466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e9a773f3b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('cbc_grade', sa.Integer(), nullable=False),
    sa.Column('parent_phone', sa.String(length=15), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_parent_phone'), ['parent_phone'], unique=True)

    op.create_table('fee_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('mpesa_receipt_number', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_transactions_mpesa_receipt_number'), ['mpesa_receipt_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_transactions_mpesa_receipt_number'))

    op.drop_table('fee_transactions')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_parent_phone'))

    op.drop_table('students')
    # ### end Alembic commands ###
